name: Feature request
labels: enhancement
body:
  - type: textarea
    id: proposal
    attributes:
      label: Describe the solution you'd like
      description: What problem does this solve?
    validations:
      required: true
